stages:
  - validate
  - plan
  - approve
  - apply


variables:
  TF_PLAN_FILE: "plan.out"
  TF_STATE_BUCKET: "sattesteu" # Change per env
  TF_STATE_KEY: "prod/terraform.tfstate"
  TF_REGION: "eu-central-1"

# Cache plugins and .terraform dir
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .terraform/


validate:
  stage: validate
  tags:
    - prod-runner # It should match the tag of the runner
  script:
    - echo "List all files and terraform validate"
    - terraform validate
    - terraform fmt -recursive

plan:
  stage: plan
  tags:
    - prod-runner

  script:
    - terraform plan -out=$TF_PLAN_FILE
  artifacts:
    paths:
      - $TF_PLAN_FILE
    expire_in: 1 hour

approve:
  stage: approve
  tags:
    - prod-runner

  when: manual
  allow_failure: false
  script:
    - echo "Manual approval required to apply changes"

apply:
  stage: apply
  tags:
    - prod-runner

  script:
    - terraform apply $TF_PLAN_FILE
